services:
#  api:
 #   build: 
  #    context: ..
   #   dockerfile: Dockerfile
    #networks:
     # - api
   # depends_on:
    #  postgres:
     #   condition: service_healthy
  postgres:
    container_name: finshark_db
    image: postgres:latest
    volumes: 
      - ../postgres-data:/var/lib/postgresql/data    
    environment:
      POSTGRES_DB: finsharkdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d finsharkdb"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - api
    restart: unless-stopped
    
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - api
    restart: unless-stopped

networks:
  api:
    name: api
    driver: bridge
